name: chessground
description: Lichess board for flutter
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.0

dev_dependencies:
  dartchess:
    git:
      url: https://github.com/lichess-org/dartchess.git
      ref: 88c3c17a5d75b8228b82339728dc99e7f1175d7c
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter:
  assets:
    - lib/piece_sets/alpha/
    - lib/piece_sets/anarcandy/
    - lib/piece_sets/california/
    - lib/piece_sets/cardinal/
    - lib/piece_sets/cburnett/
    - lib/piece_sets/celtic/
    - lib/piece_sets/chess7/
    - lib/piece_sets/chessnut/
    - lib/piece_sets/companion/
    - lib/piece_sets/disguised/
    - lib/piece_sets/dubrovny/
    - lib/piece_sets/fantasy/
    - lib/piece_sets/fresca/
    - lib/piece_sets/gioco/
    - lib/piece_sets/governor/
    - lib/piece_sets/horsey/
    - lib/piece_sets/icpieces/
    - lib/piece_sets/kosal/
    - lib/piece_sets/leipzig/
    - lib/piece_sets/letter/
    - lib/piece_sets/libra/
    - lib/piece_sets/maestro/
    - lib/piece_sets/merida/
    - lib/piece_sets/mono/
    - lib/piece_sets/pirouetti/
    - lib/piece_sets/pixel/
    - lib/piece_sets/reillycraig/
    - lib/piece_sets/riohacha/
    - lib/piece_sets/shapes/
    - lib/piece_sets/spatial/
    - lib/piece_sets/staunty/
    - lib/piece_sets/tatiana/
